### PR TITLE
Fix 227 timezone discrepancy

### LINKED ISSUE #227: Timezone discrepancy when clicking through from charts
**Describe the bug**
The formatted time appears to be off by a day when clicking through from the charts to the job explorer.

Related #218 

**To Reproduce**
1. Go to 'Clusters'
2. Click on a single bar to view Job Explorer
3. Observe that the specified day from the chart is off by one day.

**Expected behavior**
The selected dates for the charts and the job explorer should match.

**Screenshots**
timezone

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by kialam**
Fixes #227 

@Ladas @appuk 
Wondering if this change fixes the timezone off by one day issue - can you test this locally before I make the rest of the changes?

Basically we are currently converting UTC formatted date from API to local, and _then_ back to UTC, so causing an off by one day bug in the UI I think. This PR fixes the format ordering.

### CODE REVIEW

File: src/Utilities/helpers.js [hunk 1]
```diff
@@ -9,7 +9,7 @@ export function formatDateTime(dateTime) {
 }
 
 export function formatDate(date) {
-    return moment(date).utc().format('YYYY-MM-DD');
+    return moment.utc(date).format('YYYY-MM-DD');
```
Comment (Ladas) [inline src/Utilities/helpers.js:12]: looks like this function should work across the board for us, from the docs:

`moment.utc(...) is utc mode. Ambiguous input is assumed to be UTC. Unambiguous input is adjusted to UTC.`

Comment (kialam) [reply src/Utilities/helpers.js:12]: Great, thanks for checking @Ladas ! I'll go ahead and apply this formula to the rest of the areas in the UI that handle dates.

**Review by benthomasson — APPROVED** [review]
